### ISSUE TITLE
Please Wait

### ISSUE THREAD

**Issue by tykra** [Magestore/Bannerslider-Magento2#10]
When creating new slider I click save and it hangs up and never does anything.

**Comment by NicolasAndersen** [comment]
Hi tykra,
Because some file javascript of Bannerslider extension was'nt generated in folder <magento root>/pub/static/<area>/Magento/<theme>/en_US/, so you took too much time while adding slider. May be your Magento software is in default mode. You should run the Magento software in developer mode when you’re extending or customizing it. You can use this command line to show current mode :
php bin/magento deploy:mode:show
If you want to change to developer mode, you can use this command :
php bin/magento deploy:mode:set developer
