### ISSUE TITLE
My only gets in Please Wait, what to do?

### ISSUE THREAD

**Issue by Tibaus** [Magestore/Bannerslider-Magento2#11]
My only gets in "Please Wait", what to do?

![screenshot from 2016-01-12 14 40 19](https://cloud.githubusercontent.com/assets/9578204/12269822/6c13f564-b93a-11e5-829e-8c75163e1b3f.png)

**Comment by NicolasAndersen** [comment]
Because some file javascript of Bannerslider extension was'nt generated in folder <magento root>/pub/static/<area>/Magento/<theme>/en_US/, so you took too much time while adding slider. May be your Magento software is in default mode. You should run the Magento software in developer mode when you’re extending or customizing it. You can use this command line to show current mode :
php bin/magento deploy:mode:show
You need to change Magento to developer mode, you can use this command then reload the page :
php bin/magento deploy:mode:set developer

**Comment by tykra** [comment]
Had same issue ... tried over and over again to get this to work - never did!   

Installed while in Developer mode - still please wait please wait ...

Finally gave up and removed files.

**Comment by edenduong** [comment]
Hello Tykra,

The problem happened because Magento 2 must deploy the JS files to the pub/static folder. Normally, the JS files located at app\code\Magestore\Bannerslider\view, and you need to deploy it to pub/static by run the command line. If you set the developer mode, the JS files will deploy automatically when you access the website. Here is the command to set the developer mode:

php bin/magento deploy:mode:set developer

If it doesn't work, you can deploy the JS files directly by run the command:
php bin/magento setup:static-content:deploy

Regards,
